export interface IndianFoodItem {
  id: string;
  name: string;
  hindiName?: string;
  category: 'staple' | 'protein' | 'dairy' | 'vegetable' | 'pulse' | 'grain' | 'vrat';
  dietCategory: 'veg' | 'jain' | 'eggetarian' | 'non_veg';
  costPer100gInr: number;
  proteinPer100g: number;
  carbsPer100g: number;
  fatPer100g: number;
  caloriesPer100g: number;
  proteinEfficiency: number; // g protein per ₹1
  typicalServing: {
    unit: 'katori' | 'phulka' | 'mutthi' | 'chammach' | 'piece' | 'glass';
    grams: number;
    description: string;
  };
  kiranaCategory: 'Atta & Dals' | 'Dairy & Fresh' | 'Spices & Cooking Mediums' | 'Sabzi Mandi Produce';
  isVratCompatible?: boolean;
}

export const INDIAN_FOOD_DATABASE: IndianFoodItem[] = [
  {
    id: 'soya-chunks',
    name: 'Soya Chunks (Nutrela)',
    hindiName: 'सोया बड़ी',
    category: 'protein',
    dietCategory: 'veg',
    costPer100gInr: 15.0,
    proteinPer100g: 52.0,
    carbsPer100g: 33.0,
    fatPer100g: 0.5,
    caloriesPer100g: 345,
    proteinEfficiency: 3.47, // #1 Most cost-effective protein in India
    typicalServing: { unit: 'katori', grams: 35, description: '1 cooked katori' },
    kiranaCategory: 'Atta & Dals',
  },
  {
    id: 'chana-sattu',
    name: 'Roasted Chana Sattu',
    hindiName: 'चना सत्तू',
    category: 'protein',
    dietCategory: 'veg',
    costPer100gInr: 18.0,
    proteinPer100g: 22.0,
    carbsPer100g: 64.0,
    fatPer100g: 5.0,
    caloriesPer100g: 385,
    proteinEfficiency: 1.22,
    typicalServing: { unit: 'glass', grams: 40, description: '1 large sattu drink glass' },
    kiranaCategory: 'Atta & Dals',
  },
  {
    id: 'whole-eggs',
    name: 'Whole Eggs (Farm Fresh)',
    hindiName: 'अंडे',
    category: 'protein',
    dietCategory: 'eggetarian',
    costPer100gInr: 14.0, // ~₹7 per egg, 2 eggs = ~100g
    proteinPer100g: 13.0,
    carbsPer100g: 1.1,
    fatPer100g: 11.0,
    caloriesPer100g: 143,
    proteinEfficiency: 0.93,
    typicalServing: { unit: 'piece', grams: 100, description: '2 whole boiled eggs / omlette' },
    kiranaCategory: 'Dairy & Fresh',
  },
  {
    id: 'kala-chana',
    name: 'Kala Chana (Black Chickpeas)',
    hindiName: 'काला चना',
    category: 'pulse',
    dietCategory: 'veg',
    costPer100gInr: 13.0,
    proteinPer100g: 20.0,
    carbsPer100g: 60.0,
    fatPer100g: 6.0,
    caloriesPer100g: 360,
    proteinEfficiency: 1.54,
    typicalServing: { unit: 'katori', grams: 50, description: '1 katori boiled/sprouted chana' },
    kiranaCategory: 'Atta & Dals',
  },
  {
    id: 'yellow-moong-dal',
    name: 'Yellow Moong Dal (Split)',
    hindiName: 'पीली मूंग दाल',
    category: 'pulse',
    dietCategory: 'veg',
    costPer100gInr: 16.0,
    proteinPer100g: 24.0,
    carbsPer100g: 59.0,
    fatPer100g: 1.2,
    caloriesPer100g: 347,
    proteinEfficiency: 1.50,
    typicalServing: { unit: 'katori', grams: 40, description: '1 katori cooked dal' },
    kiranaCategory: 'Atta & Dals',
  },
  {
    id: 'fresh-paneer',
    name: 'Fresh Dairy Paneer',
    hindiName: 'ताज़ा पनीर',
    category: 'dairy',
    dietCategory: 'veg',
    costPer100gInr: 45.0,
    proteinPer100g: 18.0,
    carbsPer100g: 3.0,
    fatPer100g: 22.0,
    caloriesPer100g: 290,
    proteinEfficiency: 0.40,
    typicalServing: { unit: 'piece', grams: 100, description: '100g raw / grilled paneer cubes' },
    kiranaCategory: 'Dairy & Fresh',
    isVratCompatible: true,
  },
  {
    id: 'chicken-breast',
    name: 'Skinless Chicken Breast',
    hindiName: 'चिकन ब्रेस्ट',
    category: 'protein',
    dietCategory: 'non_veg',
    costPer100gInr: 30.0,
    proteinPer100g: 31.0,
    carbsPer100g: 0.0,
    fatPer100g: 3.6,
    caloriesPer100g: 165,
    proteinEfficiency: 1.03,
    typicalServing: { unit: 'piece', grams: 150, description: '150g grilled/curry breast' },
    kiranaCategory: 'Dairy & Fresh',
  },
  {
    id: 'ghar-ka-dahi',
    name: 'Ghar Ka Dahi (Set Curd)',
    hindiName: 'घर का दही',
    category: 'dairy',
    dietCategory: 'veg',
    costPer100gInr: 8.0,
    proteinPer100g: 3.5,
    carbsPer100g: 4.7,
    fatPer100g: 3.2,
    caloriesPer100g: 60,
    proteinEfficiency: 0.44,
    typicalServing: { unit: 'katori', grams: 150, description: '1 katori homemade dahi' },
    kiranaCategory: 'Dairy & Fresh',
    isVratCompatible: true,
  },
  {
    id: 'phulka-roti',
    name: 'Whole Wheat Phulka / Roti (No Ghee)',
    hindiName: 'फुल्का / सादी रोटी',
    category: 'grain',
    dietCategory: 'veg',
    costPer100gInr: 5.0,
    proteinPer100g: 9.0,
    carbsPer100g: 50.0,
    fatPer100g: 1.5,
    caloriesPer100g: 250,
    proteinEfficiency: 1.80,
    typicalServing: { unit: 'phulka', grams: 35, description: '1 medium phulka (~75 kcal, 3g P)' },
    kiranaCategory: 'Atta & Dals',
  },
  {
    id: 'steamed-rice',
    name: 'Steamed Rice (Chawal)',
    hindiName: 'उबले चावल',
    category: 'grain',
    dietCategory: 'veg',
    costPer100gInr: 6.0,
    proteinPer100g: 2.7,
    carbsPer100g: 28.0,
    fatPer100g: 0.3,
    caloriesPer100g: 130,
    proteinEfficiency: 0.45,
    typicalServing: { unit: 'katori', grams: 100, description: '1 katori steamed rice' },
    kiranaCategory: 'Atta & Dals',
  },
  {
    id: 'roasted-peanuts',
    name: 'Roasted Peanuts (Moongfali)',
    hindiName: 'भुनी मूंगफली',
    category: 'protein',
    dietCategory: 'veg',
    costPer100gInr: 16.0,
    proteinPer100g: 26.0,
    carbsPer100g: 16.0,
    fatPer100g: 49.0,
    caloriesPer100g: 567,
    proteinEfficiency: 1.63,
    typicalServing: { unit: 'mutthi', grams: 30, description: '1 mutthi (handful) snack' },
    kiranaCategory: 'Atta & Dals',
    isVratCompatible: true,
  },
  {
    id: 'roasted-makhana',
    name: 'Foxnuts / Makhana (Vrat & Snack)',
    hindiName: 'मखाना',
    category: 'vrat',
    dietCategory: 'veg',
    costPer100gInr: 70.0,
    proteinPer100g: 9.7,
    carbsPer100g: 76.0,
    fatPer100g: 0.5,
    caloriesPer100g: 347,
    proteinEfficiency: 0.14,
    typicalServing: { unit: 'katori', grams: 25, description: '1 bowl ghee-roasted makhana' },
    kiranaCategory: 'Atta & Dals',
    isVratCompatible: true,
  },
  {
    id: 'desi-ghee',
    name: 'Shuddh Desi Ghee (Cooking & Roti Topping)',
    hindiName: 'शुद्ध देसी घी',
    category: 'staple',
    dietCategory: 'veg',
    costPer100gInr: 65.0,
    proteinPer100g: 0.0,
    carbsPer100g: 0.0,
    fatPer100g: 99.5,
    caloriesPer100g: 900,
    proteinEfficiency: 0.0,
    typicalServing: { unit: 'chammach', grams: 5, description: '1 tsp atop roti or tadka (+45 kcal)' },
    kiranaCategory: 'Spices & Cooking Mediums',
    isVratCompatible: true,
  },
];
